# Generated by Django 4.2.5 on 2023-10-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='type_id',
            new_name='type',
        ),
    ]
