# Generated by Django 4.2.5 on 2023-10-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile',
            new_name='username',
        ),
    ]
