# Generated by Django 4.2.5 on 2023-10-06 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 1, 3, 52, 985110, tzinfo=datetime.timezone.utc)),
        ),
    ]
