# Generated by Django 4.2.5 on 2023-10-07 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_age_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 12, 23, 48, 118156, tzinfo=datetime.timezone.utc)),
        ),
    ]
